
<nav id="footer" data-cmsadmin-layout-footer="true">
	<$globalmenu cssClass="footer-nav" showLevels="1" alwaysShowChildren="false" showHome="false"/$>
</nav>

<div class="wrapper">	
	<span>&copy; <$date format="yyyy"/$> <$websitename/$> | <$loginstatus$><$loggedin$><a href="[logouturl]">Sign out</a><$/loggedin$><$loggedout$><a href="[loginurl]">Login</a><$/loggedout$><$/loginstatus$></span>
	<span><$social cssClass="socialMedia" /$></span>
</div>